### ISSUE TITLE
Error Messages not displaying since upgrading to Wordpress 4.7

### ISSUE THREAD

**Issue by pdab** [jfarthing84/theme-my-login#99] opened 2016-12-08 20:49 UTC
Hey Jeff,

Whenever my users mistype their login info, they aren't getting any error messages.

Is there a fix on my end or one coming?

thanks so much.  It's a great, very useful plugin.

**Comment by ssuess** [comment] 2016-12-09 13:39
same problem here

**Comment by Mallinanga** [comment] 2016-12-22 11:07
After digging into the plugin code, I figured out, that this has something to do with the is_active property in the Theme_My_Login_Template class.

Once I commented out the if ( $this->is_active() ) condition in the get_errors function, the errors started appearing again.

I think this has something to do with the shortcode output, since I believe it's the only place where the set_active( false ) is called.

For now, it's a little bit of hack commenting out the conditional directly in the plugin code, but until a fix comes out, I guess that'll have to do.

**Comment by paganJim** [comment] 2017-01-03 17:55
I am having this issue also. @Mallinanga thank you for suggesting the hack for this but I have one question.

Would I need to comment out the complete section of the function or just part of it?

Thanks!
Jim

**Comment by Mallinanga** [comment] 2017-01-03 18:28
@paganJim No. Not the whole thing. Just the conditional statement. Everything inside that check, should remain as is.

Just comment out the line that has the if ( $this->is_active() ) { and the corresponding closing bracket. }

**Comment by paganJim** [comment] 2017-01-03 18:29
Excellent.  Thank you for the very quick response!

**Comment by paganJim** [comment] 2017-01-03 18:52
I am sorry to bother you again, but unfortunately that did not work for me for some reason.

You can see what I commented out below. I believe I did as you instructed but am still having the same problem. You can view the site if you like it is at [http://jimandms.com/register/](url)

`/**
	 * Returns plugin errors
	 *
	 * @since 6.0
	 * @access public
	 */
	public function get_errors() {
		global $error;

		$theme_my_login = Theme_My_Login::get_object();

		$wp_error = $theme_my_login->errors;

		if ( empty( $wp_error ) )
			$wp_error = new WP_Error();

		// Incase a plugin uses $error rather than the $errors object
		if ( ! empty( $error ) ) {
			$wp_error->add('error', $error);
			unset($error);
		}

		$output = '';
	// 	if ( $this->is_active() ) { 
			if ( $wp_error->get_error_code() ) {
				$errors = '';
				$messages = '';
				foreach ( $wp_error->get_error_codes() as $code ) {
					$severity = $wp_error->get_error_data( $code );
					foreach ( $wp_error->get_error_messages( $code ) as $error ) {
						if ( 'message' == $severity )
							$messages .= '    ' . $error . "<br />\n";
						else
							$errors .= '    ' . $error . "<br />\n";
					}
				}
				if ( ! empty( $errors ) )
					$output .= '<p class="error">' . apply_filters( 'login_errors', $errors ) . "</p>\n";
				if ( ! empty( $messages ) )
					$output .= '<p class="message">' . apply_filters( 'login_messages', $messages ) . "</p>\n";
			}
	// 	}  
		return $output;
	}`

**Comment by Mallinanga** [comment] 2017-01-03 19:18
Do you by any chance are filtering the login_errors?
The error paragraph is showing as it should. In my case it didn't show at all.
So, I'm guessing since the error paragraph is showing, it has something to do with the apply_filters( 'login_errors', $errors )

Check if your code (or another plugin) manipulates the errors in some way.
(Probably through add_filter('login_errors' ….)

That's just a guess. It seems like your issue has another cause than mine.

**Comment by jfarthing84** [comment] 2017-01-04 22:12
It likely has something to do with your themes. I just tested with a fresh 4.7 install on TwentyFifteen and it still works as expected.

**Comment by DavidAnderson684** [comment] 2017-02-07 23:49
It works (i.e. you get to see error messages) if you are logging in from the default login page, but not if you use the shortcode on a different page. I've tested this on a default install with no other plugins.

**Comment by jfarthing84** [comment] 2017-02-19 16:59
Thanks, @DavidAnderson684, that would be the information I needed.

**Closed as completed** 2017-02-19 17:34 UTC
Labels: bug

**Comment by zagarskas** [comment] 2018-04-07 23:22
Yup, same issue here. 
Seems like everything breaks down if I to use the TML shortcode on any page other than the "defaults" that were created on first install...

To try to assist with a bit more details, install TML
Follow the examples for custom fields here:
http://docs.thememylogin.com/adding-extra-registration-fields/

then add the following short codes in various places 
Try to build custom landing pages, new pages, blog posts, widgets, whatever. 

 [theme-my-login]
 [theme-my-login default_action="login" login_template="tml-login.php"]
 [theme-my-login default_action="lostpassword" lostpassword_template="tml-lostpassword.php"]
 [theme-my-login default_action="resetpass" resetpass_template="tml-resetpass.php"]
 [theme-my-login default_action="register" register_template="tml-register.php"]
Try variations to instances such as instance="1", 2, 3 ect...

In every case there are various issues and in no cases to the error messages show up.

**To patch this without messing with the TML core** I pulled the GLOBAL WordPress error var into my local php templates and then just started coding my own error class from the ground up, and it works.

that said, the problem seems to me to be
class-theme-my-login-template.php
$this->is_active() 
$wp_error->get_error_code() 

Because when I call print_r($wp_error); in my local theme I can see the error array perfectly fine. 

PS: THANK YOU @jfarthing84 for building a great plugin that has worked well for me and my clients for MANY years. This is the _first time_ I have ever had any real issues with it. If appropriate I can post the modified version of the error class im now using ...

**Comment by jfarthing84** [comment] 2018-04-09 13:00
This issue has been closed. Can you see if the [latest development version](https://github.com/jfarthing84/theme-my-login/archive/6.4.zip) works for you?

**Comment by nmoreaud** [comment] 2018-12-04 14:47
Hello,

For information, I had the same behaviour with the last release of TML when WPML is installed too.
It is reproductible by displaying the page "my-wordpress-siteen/secondaryLanguage/login/?checkemail=confirm".
In theory, there should be a frame with the following message "Check your email for the confirmation link.". But the bug hides it.

In fact, WPML dupplicates the login page, but I cannot edit the dupplicated pages properties to set its TML action (login, register...).

The workaround was the following : 
in includes/class-theme-my-login.php, I added a filter to get the main post action.
The main language of my site is French, so this is my fix to get TML compatible with WPML :

```
	public static function get_page_action( $page ) {
		$page = apply_filters('wpml_object_id', $page, 'post', false, 'fr');
		if ( ! $page = get_post( $page ) )
			return false;

		return get_post_meta( $page->ID, '_tml_action', true );
	}
```

It would be nice to have this kind of compatibility fixes merged in the official repository.
